version: "3.9"

services:
  opa:
    image: openpolicyagent/opa:latest
    command:
      [
        "run",
        "--server",
        "--log-level",
        "debug",
        "--addr",
        "0.0.0.0:8181",
        "--watch",
        "/policies",
      ]
    volumes:
      - ./policies:/policies
    ports:
      - "8181:8181"
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
